server:
  port: 8092

jwt:
  secret: ${KEYSECRET_SECURITY:eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.nZU_gPcMXkWpkCUpJceSxS7lSickF0tTImHhAR949Z-Nt69LgW8G6lid-mqd9B579tYM8C4FN2jdhR2VRMsjtA}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}

twilio:
  accountSid: "AC2c7980bb24255cfed0e2e96bf0c8fafb"
  authToken: "ede993374055e7be78d5ea2f527d91c4"
  phoneFrom: "+13614410785"

management:
  endpoints:
    web:
      exposure:
        include: "*"